# Generated by Django 3.0.4 on 2020-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=20)),
                ('sex', models.PositiveIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')])),
                ('address', models.CharField(max_length=255)),
                ('photo_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'clients',
            },
        ),
    ]
